# Generated by Django 5.2.9 on 2025-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
